Update deployment-service1.yaml

diff --git a/deployment-service1.yaml b/deployment-service1.yaml
--- a/deployment-service1.yaml
+++ b/deployment-service1.yaml
@@ -5,7 +5,7 @@ metadata:
   namespace: wireguard
 spec:
   serviceName: "node-wireguard"
-  replicas: 3
+  replicas: 5
   selector:
     matchLabels:
       app: node-wireguard
@@ -14,16 +14,16 @@ spec:
       labels:
         app: node-wireguard
     spec:
-      hostNetwork: true
-      dnsPolicy: None
-      dnsConfig:
-        nameservers:
-          - 8.8.8.8
-          - 1.1.1.1
-        searches:
-          - wireguard.svc.cluster.local
-          - svc.cluster.local
-          - cluster.local
+      # hostNetwork: true
+      # dnsPolicy: None
+      # dnsConfig:
+      #   nameservers:
+      #     - 8.8.8.8
+      #     - 1.1.1.1
+      #   searches:
+      #     - wireguard.svc.cluster.local
+      #     - svc.cluster.local
+      #     - cluster.local
       serviceAccountName: jenkins
       initContainers:
         - name: wireguard-setup
@@ -52,22 +52,22 @@ spec:
               PRIVATE_KEY=$(wg genkey)
               PUBLIC_KEY=$(echo "$PRIVATE_KEY" | wg pubkey)
 
-              # # Extract pod index from pod name 
-              # if [[ -z "$POD_NAME" ]]; then
-              #   echo "Error: POD_NAME is not set"
-              #   exit 1
-              # fi
+              # Extract pod index from pod name 
+              if [[ -z "$POD_NAME" ]]; then
+                echo "Error: POD_NAME is not set"
+                exit 1
+              fi
 
-              # POD_INDEX=$(echo "$POD_NAME" | grep -oE '[0-9]+$')
-              # if [[ -z "$POD_INDEX" ]]; then
-              #   echo "Error: Failed to extract POD_INDEX from POD_NAME"
-              #   exit 1
-              # fi
+              POD_INDEX=$(echo "$POD_NAME" | grep -oE '[0-9]+$')
+              if [[ -z "$POD_INDEX" ]]; then
+                echo "Error: Failed to extract POD_INDEX from POD_NAME"
+                exit 1
+              fi
 
               
-              # LISTEN_PORT=$((51820 + POD_INDEX))
-              LISTEN_PORT=51820 
-              # PEER_IP="10.8.0.$((1 + POD_INDEX)"
+              LISTEN_PORT=$((51820 + POD_INDEX))
+              # LISTEN_PORT=51820 
+              PEER_IP="10.8.0.$((1 + POD_INDEX)"
               PEER_IP="10.8.0.1"
 
               # Save the private and public keys to the container
@@ -111,14 +111,14 @@ spec:
               protocol: TCP
             - containerPort: 51820
               protocol: UDP
-            # - containerPort: 51821
-            #   protocol: UDP
-            # - containerPort: 51822
-            #   protocol: UDP
-            # - containerPort: 51823
-            #   protocol: UDP
-            # - containerPort: 51824
-            #   protocol: UDP
+            - containerPort: 51821
+              protocol: UDP
+            - containerPort: 51822
+              protocol: UDP
+            - containerPort: 51823
+              protocol: UDP
+            - containerPort: 51824
+              protocol: UDP
           env:
             - name: NODE_ENV
               value: production
@@ -173,26 +173,26 @@ spec:
       port: 51820
       targetPort: 51820
       nodePort: 30002  # NodePort for pod 0
-    # - name: udp-traffic-51821
-    #   protocol: UDP
-    #   port: 51821
-    #   targetPort: 51821
-    #   nodePort: 30003  # NodePort for pod 1
-    # - name: udp-traffic-51822
-    #   protocol: UDP
-    #   port: 51822
-    #   targetPort: 51822
-    #   nodePort: 30004  # NodePort for pod 2
-    # - name: udp-traffic-51823
-    #   protocol: UDP
-    #   port: 51823
-    #   targetPort: 51823
-    #   nodePort: 30005  # NodePort for pod 3
-    # - name: udp-traffic-51824
-    #   protocol: UDP
-    #   port: 51824
-    #   targetPort: 51824
-    #   nodePort: 30006  # NodePort for pod 4
+    - name: udp-traffic-51821
+      protocol: UDP
+      port: 51821
+      targetPort: 51821
+      nodePort: 30003  # NodePort for pod 1
+    - name: udp-traffic-51822
+      protocol: UDP
+      port: 51822
+      targetPort: 51822
+      nodePort: 30004  # NodePort for pod 2
+    - name: udp-traffic-51823
+      protocol: UDP
+      port: 51823
+      targetPort: 51823
+      nodePort: 30005  # NodePort for pod 3
+    - name: udp-traffic-51824
+      protocol: UDP
+      port: 51824
+      targetPort: 51824
+      nodePort: 30006  # NodePort for pod 4
 
 
 
